package com.etmr.course.model;

import javax.persistence.Entity;
import java.util.Date;

/**
 * Course generated by hbm2java
 */
@Entity
public class Course implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7622557127358894403L;

	private int course_id;
	private int testroom_id;
	private int classroom_id;
	private String name;
	private Date start_time;
	private Date end_time;
	private String speaker;
	private String remark;
	private int status;
	private int delete_flag;

	public int getCourse_id() {
		return course_id;
	}

	public void setCourse_id(int course_id) {
		this.course_id = course_id;
	}

	public int getTestroom_id() {
		return testroom_id;
	}

	public void setTestroom_id(int testroom_id) {
		this.testroom_id = testroom_id;
	}

	public int getClassroom_id() {
		return classroom_id;
	}

	public void setClassroom_id(int classroom_id) {
		this.classroom_id = classroom_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public Date getStart_time() {
		return start_time;
	}

	public void setStart_time(Date start_time) {
		this.start_time = start_time;
	}

	public Date getEnd_time() {
		return end_time;
	}

	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}
	

	public String getSpeaker() {
		return speaker;
	}

	public void setSpeaker(String speaker) {
		this.speaker = speaker;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getDelete_flag() {
		return delete_flag;
	}

	public void setDelete_flag(int delete_flag) {
		this.delete_flag = delete_flag;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Course() {
	}

	public Course(Integer testroom_id, Integer classroom_id, String name, Date start_time, Date end_time,
			String speaker, String remark, int status, int delete_flag) {
		this.testroom_id = testroom_id;
		this.classroom_id = classroom_id;
		this.name = name;
		this.start_time = start_time;
		this.end_time = end_time;
		this.speaker = speaker;
		this.remark = remark;
		this.status = status;
		this.delete_flag = delete_flag;
	}

}
